### PR TITLE
Update p4d.py

### PR DESCRIPTION
**Pull request by smalltoe**
make port available to be passed from outside

### CODE REVIEW

**Comment by ibrewster** [comment]
Good idea, but just looking at the changes (I haven't tested them yet), I see two potential issues:

1. It looks like you replace the hardcoded port with the one passed in, which is good, but I don't see where you specified a default to be used if no port is given, which would break any existing code that assumes a default port value.
2. It would appear you expect the passed in port to be a string value, where before it was an integer. This may actually work - as mentioned I haven't tested it - but at the very least it "feels" wrong to me. It seems to me that port should be an integer. Can you comment on this?

**Comment by smalltoe** [comment]
Hi Israel, I admit I am very new to all this github thing and not very experienced.

To your points:
1 Is this not assured with def connect(dsn=None, ....., port=None):?
2 Now thinktng about it - I agree. I had a wrong thought while writing it down.

Let me amend, and test again. I can get back to you on Monday.

Thanks

Smalltoe

**Comment by ibrewster** [comment]
The python code is good with port=None, but I think the problem would arise when you try to call lib4d_sql.fourd_connect(...) with no port specified (which would be the result of leaving port=None). Notice that before I had that hard-coded at 19812. I think the easiest and cleanest approach here is to simply replace port=None with port=19812 in the connect call. Then, rather than defaulting to none, it defaults to 19812, which is what the original code had (and, I believe, what the default for 4D is).

**Comment by smalltoe** [comment]
Hi, I updated and tested the code. Hope you agree with all the changes. Always happy to improve!

**Comment by ibrewster** [comment]
Looks good, thanks! I think I'll wrap the `connect_args['port'] = int(port)` line in a try/except block, just in case someone tries something fancy like passing '4d' for the port, but the changes themselves look fine. Changes merged.

**Comment by smalltoe** [comment]
Great! Thanks a lot!

**Pull request merged**
